name: Build

on:
  create:
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build-open-wbo:
    name: Build Open-WBO
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        platform: [linux]
        include:
          - platform: linux
            os: ubuntu-latest
    steps:
      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: hbierlee/open-wbo-builds
      - name: Prepare build environment
        id: prepare
        run: sudo apt-get update
      - name: Fetch Open-WBO
        run: | 
          mkdir ${{ github.workspace }}/dist
          cd ${{ github.workspace }}/dist
          git clone git@github.com:sat-group/open-wbo.git
      - name: Build Open-WBO
        run: |
          cd ${{ github.workspace }}/dist/open-wbo
          make r
      - name: Add licenses
        run: cp ./LICENSE ./dist/open-wbo-*
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: open-wbo_release
          path: ${{ github.workspace }}/dist/*

