name: Build

on: create
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build-open-wbo:
    name: Build Open-WBO
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        platform: [linux]
        include:
          - platform: linux
            os: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare build environment
        id: prepare
        run: sudo apt-get update
        env:
          OPEN_WBO_PLATFORM: ${{ matrix.platform }}
        working-directory: scripts
      - name: Fetch Open-WBO
        run: git clone git@github.com:sat-group/open-wbo.git
      - name: Build Open-WBO
        run: make rs
      - name: Add licenses
        run: cp ./LICENSE ./dist/open-wbo-*
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: open-wbo_release
          path: ${{ github.workspace }}/dist/*

