name: Build

on:
  create:
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build-open-wbo:
    name: Build Open-WBO
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        platform: [linux]
        include:
          - platform: linux
            os: ubuntu-latest
    steps:
      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: hbierlee/open-wbo-builds
      - name: Prepare build environment
        id: prepare
        run: sudo apt-get update
      - name: Fetch Open-WBO
        run: | 
          mkdir dist
          cd dist
          git clone git@github.com:sat-group/open-wbo.git
      - name: Build Open-WBO
        run: |
          cd dist/open-wbo
          make r
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: open-wbo
          path: dist/*

  release:
    name: Create release
    needs: [build-open-wbo]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: open-wbo
          path: artifacts
      - name: Package artifacts
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/package"  
          for d in *; do
            cd "$d"
            tar -czvf "${GITHUB_WORKSPACE}/package/${d}.tar.gz" *
            cd -
          done
        working-directory: artifacts
      - name: Create release
        run: |
          set -x
          build_type="$(basename $(dirname ${GITHUB_REF}))"
          build_version="$(basename ${GITHUB_REF})"
          tag="$build_type/$build_version"
          label="$build_type/$(date +'%Y-%m-%d')"
          for asset in ${GITHUB_WORKSPACE}/package/*.tar.gz; do
            flags+=("-a" "$asset")
          done
          hub release create "${flags[@]}" -m "Open-WBO ${label}" "${tag}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

