name: Trigger

on:
  schedule:
    - cron: "0 19 * * *"
  repository_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  trigger:
    name: Trigger builds
    runs-on: ubuntu-latest
    steps:
      - name: Setup git access to allow triggering build workflow
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --global user.email "<>"
          git config --global user.name "Automatic Build"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Tag nightly open-wbo build if necessary
        run: |
          sha=$(git ls-remote https://github.com/sat-group/open-wbo refs/heads/master | awk '{print $1;}')
          night=$(date +'%Y-%m-%d')          
          echo "Pushing tag for nightly $sha"
          git tag -a "nightly/$sha" -m "Open-WBO nightly ($night)"
          git push -f origin "nightly/$sha"
